# Generated by Django 6.0.4 on 2026-04-21 01:23

import cloudinary.models
import common.validators
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmedia",
            name="image",
            field=cloudinary.models.CloudinaryField(
                folder="posts/media",
                max_length=255,
                validators=[common.validators.validate_image_upload],
                verbose_name="image",
            ),
        ),
    ]
