# Generated by Django 6.0.4 on 2026-04-20 21:52

import common.utils
import common.validators
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlumniProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "full_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "student_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "class_roll",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "batch_year",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Primary batch/search year used in directory filters.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1950),
                            django.core.validators.MaxValueValidator(2031),
                        ],
                    ),
                ),
                (
                    "academic_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("science", "Science"),
                            ("business_studies", "Business Studies"),
                            ("humanities", "Humanities"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "ssc_passing_year",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1950),
                            django.core.validators.MaxValueValidator(2031),
                        ],
                    ),
                ),
                ("ssc_school_name", models.CharField(blank=True, max_length=255)),
                (
                    "hsc_passing_year",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1950),
                            django.core.validators.MaxValueValidator(2031),
                        ],
                    ),
                ),
                ("hsc_school_name", models.CharField(blank=True, max_length=255)),
                ("bio", models.TextField(blank=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=common.utils.UploadToPath("profiles", "pictures"),
                        validators=[common.validators.validate_image_upload],
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=30)),
                ("present_address", models.TextField(blank=True)),
                ("permanent_address", models.TextField(blank=True)),
                (
                    "current_city",
                    models.CharField(blank=True, db_index=True, max_length=150),
                ),
                (
                    "current_country",
                    models.CharField(blank=True, db_index=True, max_length=150),
                ),
                ("social_links", models.JSONField(blank=True, default=dict)),
                (
                    "directory_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("alumni_only", "Alumni Only"),
                            ("private", "Private"),
                        ],
                        db_index=True,
                        default="alumni_only",
                        max_length=20,
                    ),
                ),
                (
                    "email_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("alumni_only", "Alumni Only"),
                            ("private", "Private"),
                        ],
                        default="alumni_only",
                        max_length=20,
                    ),
                ),
                (
                    "phone_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("alumni_only", "Alumni Only"),
                            ("private", "Private"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                (
                    "social_link_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("alumni_only", "Alumni Only"),
                            ("private", "Private"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["full_name", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlumniVerificationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("review_note", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
