# Generated by Django 6.0.4 on 2026-04-21 01:23

import cloudinary.models
import common.validators
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumniprofile",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                folder="profiles/pictures",
                max_length=255,
                null=True,
                validators=[common.validators.validate_image_upload],
                verbose_name="image",
            ),
        ),
    ]
