# Generated by Django 6.0.4 on 2026-04-20 21:52

import django.core.validators
import django.utils.timezone
import users.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(blank=True, max_length=150)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("moderator", "Moderator"),
                            ("staff", "Staff"),
                            ("alumni", "Alumni"),
                            ("guest", "Guest User / Current Student"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("rejected", "Rejected"),
                            ("deactivated", "Deactivated"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "managed_batch_year",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Used for batch-wise staff scoping.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1950),
                            django.core.validators.MaxValueValidator(2031),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Institution or moderator verified alumni/member flag.",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["role", "account_status"],
                        name="users_user_role_1f6047_idx",
                    ),
                    models.Index(
                        fields=["is_active", "is_verified"],
                        name="users_user_is_acti_d093de_idx",
                    ),
                    models.Index(
                        fields=["managed_batch_year"],
                        name="users_user_managed_ccea82_idx",
                    ),
                ],
            },
            managers=[
                ("objects", users.managers.UserManager()),
            ],
        ),
    ]
