# Generated by Django 6.0.4 on 2026-04-20 21:52

import common.utils
import common.validators
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("eftar_party", "Eftar Party"),
                            ("reunion", "Reunion"),
                            ("sports_carnival", "Sports Carnival"),
                            ("custom_event", "Custom Event"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("event_name", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=280, unique=True)),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=common.utils.UploadToPath("events", "banners"),
                        validators=[common.validators.validate_image_upload],
                    ),
                ),
                ("invitation_letter", models.TextField(blank=True)),
                (
                    "batch",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("season", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2031),
                        ],
                    ),
                ),
                ("event_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "event_start_date",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "event_end_date",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("location", models.CharField(db_index=True, max_length=255)),
                ("gathering_time", models.TimeField(blank=True, null=True)),
                (
                    "registration_start_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("registration_end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("through_admin", "Through Admin"),
                            ("through_batch_staff", "Through Batch Staff"),
                            ("no_payment_required", "No Payment Required"),
                        ],
                        db_index=True,
                        default="no_payment_required",
                        max_length=30,
                    ),
                ),
                ("generate_registration_pdf", models.BooleanField(default=False)),
                ("generate_ticket_or_checkin_pdf", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(db_index=True, default=True)),
                ("creator_role", models.CharField(blank=True, max_length=20)),
                ("sponsor_support_enabled", models.BooleanField(default=False)),
                (
                    "participant_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("alumni_only", "Alumni Only"),
                            ("private", "Private"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-event_start_date", "-event_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventGallery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to=common.utils.UploadToPath("events", "gallery"),
                        validators=[common.validators.validate_image_upload],
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("is_public", models.BooleanField(db_index=True, default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("attended", "Attended"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("not_required", "Not Required"),
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="not_required",
                        max_length=20,
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=255)),
                ("note", models.TextField(blank=True)),
                (
                    "attendee_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("alumni_only", "Alumni Only"),
                            ("private", "Private"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "ticket_code",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("pdf_generated_at", models.DateTimeField(blank=True, null=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("result_summary", models.TextField()),
                ("highlights", models.JSONField(blank=True, default=list)),
                ("post_event_information", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=common.utils.UploadToPath("events", "results"),
                        validators=[common.validators.validate_document_upload],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("removed", "Removed"),
                        ],
                        db_index=True,
                        default="approved",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventSponsor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sponsor_name", models.CharField(db_index=True, max_length=255)),
                (
                    "sponsor_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=common.utils.UploadToPath("events", "sponsors"),
                        validators=[common.validators.validate_image_upload],
                    ),
                ),
            ],
            options={
                "ordering": ["sponsor_name"],
            },
        ),
    ]
