# Generated by Django 6.0.4 on 2026-04-21 01:23

import cloudinary.models
import common.validators
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="banner",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                folder="events/banners",
                max_length=255,
                null=True,
                validators=[common.validators.validate_image_upload],
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="eventgallery",
            name="image",
            field=cloudinary.models.CloudinaryField(
                folder="events/gallery",
                max_length=255,
                validators=[common.validators.validate_image_upload],
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="eventresult",
            name="attachment",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                folder="events/results",
                max_length=255,
                null=True,
                resource_type="raw",
                validators=[common.validators.validate_document_upload],
                verbose_name="raw",
            ),
        ),
        migrations.AlterField(
            model_name="eventsponsor",
            name="sponsor_logo",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                folder="events/sponsors",
                max_length=255,
                null=True,
                validators=[common.validators.validate_image_upload],
                verbose_name="image",
            ),
        ),
    ]
