# Generated by Django 6.0.4 on 2026-04-20 21:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("present_occupation", models.CharField(db_index=True, max_length=255)),
                ("role", models.CharField(db_index=True, max_length=255)),
                (
                    "institution_or_organization_name",
                    models.CharField(db_index=True, max_length=255),
                ),
                ("starting_date", models.DateField()),
                ("ending_date", models.DateField(blank=True, null=True)),
                (
                    "currently_working_here",
                    models.BooleanField(db_index=True, default=False),
                ),
            ],
            options={
                "ordering": [
                    "-currently_working_here",
                    "-starting_date",
                    "-created_at",
                ],
            },
        ),
    ]
